### PR TITLE
0.1 Versioning (PR - redo)

### PR DESCRIPTION
**Pull request by Marklon**
Made a copy of the files moved those files to 0.1 folder and left the root of the repo as is

### CODE REVIEW

**Comment by sekka1** [comment]
Cool...that looks better.  Have you ran a docker build on both the root and towards the `0.1` folder?  Does it work?

**Comment by Marklon** [comment]
This is the error I received below. @sekka1 

> docker run garland/docker-s3cmd
**ERROR: The environment variable key is not set.**
+ S3CMD_PATH=/opt/s3cmd/s3cmd
+ [ -z  ]
+ echo ERROR: The environment variable key is not set.
+ exit 1 > 


I'm positive I set my ENV AWS_KEY along with the AWS_SECRET. (Keys below are not the real outputs)

admin$ echo $AWS_SECRET
We9edffsdDUzifdffd8jekKHye7sKm4VJaH
admin$ echo $AWS_KEY
JEJDEOOWLWKEETOGA

**Comment by sekka1** [comment]
No build errors?

Can you give me the starting docker run command without your keys in there?  Also, you should really delete that key now above =)  This is all public.

**Comment by sekka1** [comment]
Cool...ive tested it and it works.  

Thanks @Marklon

**Pull request merged**
